create extension if not exists pgcrypto;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  username text not null unique check (username ~ '^[A-Za-z0-9가-힣_-]{2,16}$'),
  password_hash text not null,
  created_at timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.guestbook_comments (
  id bigint generated by default as identity primary key,
  guestbook_id bigint not null references public.guestbook(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.typing_scores (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  username text not null,
  cpm integer not null check (cpm between 0 and 1200),
  accuracy numeric(5,2) not null check (accuracy between 0 and 100),
  score integer not null check (score between 0 and 1200),
  created_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.guestbook enable row level security;
alter table public.guestbook_comments enable row level security;
alter table public.typing_scores enable row level security;

revoke all on public.players from anon, authenticated;
revoke insert, update, delete on public.guestbook from anon, authenticated;
revoke insert, update, delete on public.guestbook_comments from anon, authenticated;
revoke insert, update, delete on public.typing_scores from anon, authenticated;
grant select on public.guestbook, public.guestbook_comments, public.typing_scores to anon, authenticated;

drop policy if exists "public guestbook read" on public.guestbook;
create policy "public guestbook read" on public.guestbook for select to anon, authenticated using (true);
drop policy if exists "public guestbook comments read" on public.guestbook_comments;
create policy "public guestbook comments read" on public.guestbook_comments for select to anon, authenticated using (true);
drop policy if exists "public score read" on public.typing_scores;
create policy "public score read" on public.typing_scores for select to anon, authenticated using (true);

create or replace function public.verify_player(p_username text, p_password text)
returns bigint language plpgsql security definer set search_path = public, extensions as $$
declare v_player public.players;
begin
  if p_username !~ '^[A-Za-z0-9가-힣_-]{2,16}$' then raise exception '아이디는 2~16자의 문자, 숫자, _, -만 사용할 수 있습니다.'; end if;
  if char_length(p_password) < 4 or char_length(p_password) > 32 then raise exception '비밀번호는 4~32자로 입력해 주세요.'; end if;
  select * into v_player from public.players where username = p_username;
  if not found then
    insert into public.players(username, password_hash) values (p_username, crypt(p_password, gen_salt('bf'))) returning id into v_player.id;
    return v_player.id;
  end if;
  if v_player.password_hash <> crypt(p_password, v_player.password_hash) then raise exception '아이디 또는 비밀번호가 올바르지 않습니다.'; end if;
  update public.players set last_active_at = now() where id = v_player.id;
  return v_player.id;
end; $$;

create or replace function public.add_guestbook(p_username text, p_password text, p_message text)
returns bigint language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint; v_id bigint;
begin
  if char_length(trim(p_message)) < 1 or char_length(trim(p_message)) > 120 then raise exception '메시지는 1~120자로 입력해 주세요.'; end if;
  v_player_id := public.verify_player(p_username, p_password);
  if exists(select 1 from public.guestbook where player_id=v_player_id and created_at > now()-interval '10 seconds') then raise exception '잠시 후 다시 작성해 주세요.'; end if;
  insert into public.guestbook(player_id,username,message) values(v_player_id,p_username,trim(p_message)) returning id into v_id;
  return v_id;
end; $$;

create or replace function public.submit_typing_score(p_username text, p_password text, p_cpm integer, p_accuracy numeric)
returns bigint language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint; v_score integer; v_id bigint;
begin
  if p_cpm < 0 or p_cpm > 1200 or p_accuracy < 0 or p_accuracy > 100 then raise exception '유효하지 않은 게임 기록입니다.'; end if;
  v_player_id := public.verify_player(p_username,p_password);
  if exists(select 1 from public.typing_scores where player_id=v_player_id and created_at > now()-interval '5 seconds') then raise exception '잠시 후 다시 도전해 주세요.'; end if;
  v_score := p_cpm;
  insert into public.typing_scores(player_id,username,cpm,accuracy,score) values(v_player_id,p_username,p_cpm,p_accuracy,v_score) returning id into v_id;
  return v_id;
end; $$;

create or replace function public.add_guestbook_comment(p_guestbook_id bigint, p_username text, p_password text, p_message text)
returns bigint language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint; v_id bigint;
begin
  if char_length(trim(p_message)) < 1 or char_length(trim(p_message)) > 120 then raise exception '댓글은 1~120자로 입력해 주세요.'; end if;
  if not exists(select 1 from public.guestbook where id = p_guestbook_id) then raise exception '존재하지 않는 방문 기록입니다.'; end if;
  v_player_id := public.verify_player(p_username, p_password);
  if exists(select 1 from public.guestbook_comments where player_id=v_player_id and created_at > now()-interval '10 seconds') then raise exception '잠시 후 다시 작성해 주세요.'; end if;
  insert into public.guestbook_comments(guestbook_id,player_id,username,message) values(p_guestbook_id,v_player_id,p_username,trim(p_message)) returning id into v_id;
  return v_id;
end; $$;

create or replace function public.update_guestbook(p_id bigint, p_username text, p_password text, p_message text)
returns boolean language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint;
begin
  if char_length(trim(p_message)) < 1 or char_length(trim(p_message)) > 120 then raise exception '메시지는 1~120자로 입력해 주세요.'; end if;
  v_player_id := public.verify_player(p_username, p_password);
  update public.guestbook set message = trim(p_message) where id = p_id and player_id = v_player_id;
  if not found then raise exception '수정할 수 없는 방명록입니다.'; end if;
  return true;
end; $$;

create or replace function public.delete_guestbook(p_id bigint, p_username text, p_password text)
returns boolean language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint;
begin
  v_player_id := public.verify_player(p_username, p_password);
  delete from public.guestbook where id = p_id and player_id = v_player_id;
  if not found then raise exception '삭제할 수 없는 방명록입니다.'; end if;
  return true;
end; $$;

create or replace function public.delete_guestbook_comment(p_id bigint, p_username text, p_password text)
returns boolean language plpgsql security definer set search_path = public, extensions as $$
declare v_player_id bigint;
begin
  v_player_id := public.verify_player(p_username, p_password);
  delete from public.guestbook_comments where id = p_id and player_id = v_player_id;
  if not found then raise exception '삭제할 수 없는 댓글입니다.'; end if;
  return true;
end; $$;

grant execute on function public.add_guestbook(text,text,text) to anon, authenticated;
grant execute on function public.add_guestbook_comment(bigint,text,text,text) to anon, authenticated;
grant execute on function public.submit_typing_score(text,text,integer,numeric) to anon, authenticated;
grant execute on function public.update_guestbook(bigint,text,text,text) to anon, authenticated;
grant execute on function public.delete_guestbook(bigint,text,text) to anon, authenticated;
grant execute on function public.delete_guestbook_comment(bigint,text,text) to anon, authenticated;
revoke execute on function public.verify_player(text,text) from public, anon, authenticated;
